name: llm2
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - expat=2.7.1=h313beb8_0
  - libcxx=20.1.8=h8869778_0
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.2=pyhc872135_1
  - python=3.11.13=h19e8193_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - arxiv==2.2.0
      - attrs==25.4.0
      - backoff==2.2.1
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - brotli==1.1.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cssselect2==0.8.0
      - cycler==0.12.1
      - dashscope==1.24.6
      - dataclasses-json==0.6.7
      - datasets==2.18.0
      - deprecation==2.1.0
      - dill==0.3.8
      - distro==1.9.0
      - docopt==0.6.2
      - duckduckgo-search==8.1.1
      - emoji==2.15.0
      - fastapi==0.119.0
      - fastuuid==0.13.5
      - feedparser==6.0.12
      - filelock==3.20.0
      - filetype==1.2.0
      - fire==0.5.0
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2024.2.0
      - greenlet==3.2.4
      - h11==0.16.0
      - h2==4.3.0
      - hf-xet==1.1.10
      - hpack==4.1.0
      - html5lib==1.1
      - htmldocx==0.0.6
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-aiohttp==0.1.9
      - httpx-sse==0.4.3
      - huggingface-hub==0.35.3
      - hyperframe==6.1.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.11.0
      - joblib==1.5.2
      - json-repair==0.52.0
      - json5==0.12.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - langchain==1.1.0
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.1.0
      - langchain-mcp-adapters==0.1.11
      - langchain-ollama==1.0.0
      - langchain-openai==1.1.0
      - langchain-text-splitters==1.0.0
      - langdetect==1.0.9
      - langgraph==1.0.4
      - langgraph-checkpoint==2.1.2
      - langgraph-cli==0.4.3
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.9
      - langsmith==0.4.37
      - levenshtein==0.25.0
      - litellm==1.78.2
      - loguru==0.7.3
      - lxml==6.0.2
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markdown2==2.5.4
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - mcp==1.17.0
      - md2pdf==1.0.1
      - mdurl==0.1.2
      - mistune==3.1.4
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - nltk==3.9.2
      - numpy==2.2.6
      - olefile==0.47
      - ollama==0.6.0
      - openai==2.8.1
      - opencv-python==4.9.0.80
      - orjson==3.11.3
      - ormsgpack==1.11.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==10.2.0
      - postgrest==2.24.0
      - primp==0.15.0
      - propcache==0.4.1
      - psutil==7.1.0
      - pyarrow==22.0.0
      - pyarrow-hotfix==0.7
      - pycparser==2.23
      - pydantic==2.12.2
      - pydantic-core==2.41.4
      - pydantic-settings==2.11.0
      - pydyf==0.11.0
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pymupdf==1.26.5
      - pyparsing==3.2.5
      - pypdf==6.1.1
      - pyphen==0.17.2
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-dotenv==1.1.1
      - python-iso639==2025.2.18
      - python-levenshtein==0.25.0
      - python-magic==0.4.27
      - python-multipart==0.0.20
      - python-oxmsg==0.0.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - rapidfuzz==3.14.1
      - realtime==2.24.0
      - referencing==0.37.0
      - regex==2025.9.18
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==13.7.1
      - rpds-py==0.27.1
      - seaborn==0.13.2
      - sgmllib3k==1.0.0
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - sse-starlette==3.0.2
      - starlette==0.48.0
      - storage3==2.24.0
      - strenum==0.4.15
      - supabase==2.24.0
      - supabase-auth==2.24.0
      - supabase-functions==2.24.0
      - tavily-python==0.7.12
      - tenacity==9.1.2
      - termcolor==3.2.0
      - tiktoken==0.12.0
      - tinycss2==1.4.0
      - tinyhtml5==2.0.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - unstructured==0.18.15
      - unstructured-client==0.42.3
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - weasyprint==66.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - win32-setctime==1.2.0
      - word2number==1.1
      - wrapt==1.17.3
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zopfli==0.2.3.post1
      - zstandard==0.25.0
prefix: /Users/chz/anaconda3/envs/llm2
